apiVersion: keda.k8s.io/v1alpha1
kind: ScaledObject
metadata:
  name: my-scaledobject
  namespace: default
  labels:
    deploymentName: my-dep
spec:
  pollingInterval: 10   # Optional. Default: 30 seconds
  cooldownPeriod: 100  # Optional. Default: 300 seconds
  minReplicaCount: 0   # Optional. Default: 0
  maxReplicaCount: 30  # Optional. Default: 100  
  scaleTargetRef:
    deploymentName: my-dep
    namespace: default
  triggers:
  - type: external
    metadata:
      targetSize: "1"
      scalerAddress: my-scaler-service.default.svc.cluster.local:80
      urlOfService: http://mockserver.mockserver.svc.cluster.local:1080/fake
      
