apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-dep
  namespace: default
spec:
  selector:
    matchLabels:
      app: my-dep
  replicas: 1
  template:
    metadata:
      labels:
        app: my-dep
    spec:
      containers:
      - name: my-dep
        image: mcr.microsoft.com/azuredocs/aci-helloworld
        imagePullPolicy: Always